##################### Storage #####################
dataset_name : "image"
folder_image : "./storage/dataset/archive/images"
file_caption : "./storage/dataset/captions/captions.txt"
folder_train_log : "./storage/log"
folder_test_log : "./storage/log"
folder_model : "./storage/model"

##################### Architecture #####################
load_model_trained : False

##################### Hyper Params #####################
lr : 0.001
wd : 0.01
batch_size : 10
epoches : 30